config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'lists#index'

  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }

end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to lists_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for([list, bookmark]) do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/bookmarks/new.html.erb
<h1>Add a bookmark</h1>
<%= render "form", list: @list, bookmark: @bookmark %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://img.freepik.com/free-vector/movie-theater-stage-cinema-empty-theatre-scene_107791-15928.jpg);">
  <div class="container">
    <h1>Save your <strong>Favorite</strong> Movies!</h1>
  </div>
</div>

<div class="container">
  <h2 class="mt-4">My Lists</h2>
  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-12 mt-4 col-md-4">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://img.freepik.com/premium-photo/old-parchment-paper-scroll-sheet-vintage-aged-texture-isolated-white-background_34266-2090.jpg)">
          🍿 <%= list.name %> - <%= link_to "See Detail", list_path(list) %>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "Create a new list", new_list_path, class: "btn btn-primary mt-4" %>

   <% @lists.each do |list| %>
      <% if list.photo.attached? %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
          <%= list.name %>
        </div>
      <% else %>
        <h2><%= list.name %></h2>
      <% end %>
      <div class="row">
        <% list.bookmarks.each do |bookmark| %>
          <div class="col-12 col-md-4 mt-4">
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= bookmark.movie.poster_url %>')">
              <div><%= bookmark.movie.title %></div>
              <div><%= link_to "Delete Movie", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger" %></div>
            </div>
          </div>
        <% end %>
      </div>

      <%= link_to "Add a Movie",new_list_bookmark_path(list), class: "btn btn-primary my-3" %>
    <% end %>
</div>

app/views/lists/new.html.erb
<h1>Create a new List</h1>
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<h2>Movies Associated with this list:</h2>
  <% @list.bookmarks.each do |bookmark| %>
    <div class="card-product my-3">
      <img src='<%= bookmark.movie.poster_url %>'/>
      <div class="d-flex justify-content-between">
        <div class="card-product-infos">
          <h2><%= bookmark.movie.title %></h2>
          <p>Comment about the movie: <strong><%= bookmark.comment %></strong></p>
        </div>
        <div>
          <%= link_to "Delete Movie", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  <% end %>
<%= link_to "Add a movie", new_list_bookmark_path(@list), class: "btn btn-primary" %>
<%= link_to "Back to List Overview", lists_path, class: "btn btn-primary" %>